/*
 * File: app/view/main/MainNorth.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Ehm.view.main.MainNorth', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.main_north',

    requires: [
        'Ehm.view.main.MainNorthViewModel',
        'Ehm.view.main.MainNorthViewController',
        'Ext.form.Panel',
        'Ext.Img',
        'Ext.button.Segmented',
        'Ext.button.Button',
        'Ext.toolbar.Spacer',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Fill'
    ],

    controller: 'main_north',
    viewModel: {
        type: 'main_north'
    },
    layout: 'column',

    items: [
        {
            xtype: 'form',
            height: 74,
            width: 250,
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'image',
                    flex: 1,
                    padding: '30 40 15 25',
                    src: './resources/ehm_images/Images/ENote_20140811.png'
                }
            ]
        },
        {
            xtype: 'segmentedbutton',
            height: 80,
            margin: '0 0 0 20',
            padding: '13 0 0 0',
            width: 600,
            defaults: {
                border: 0
            },
            items: [
                /**{
                    handler: function(button, e) {
                        var button = Ext.ComponentQuery.query('[itemId=a1]')[0];
                        button.expand();
                    },
                    cls: 'btn1',
                    itemId: 'mybutton'
                },
                {
                    handler: function(button, e) {
                        var button = Ext.ComponentQuery.query('[itemId=a2]')[0];
                        button.expand();
                    },
                    cls: 'btn2'
                },
                {
                    handler: function(button, e) {
                        var button = Ext.ComponentQuery.query('[itemId=a3]')[0];
                        button.expand();
                    },
                    cls: 'btn3'
                },
                {
                    handler: function(button, e) {
                        var button = Ext.ComponentQuery.query('[itemId=a4]')[0];
                        button.expand();
                    },
                    cls: 'btn4'
                },
                {
                    handler: function(button, e) {
                        var button = Ext.ComponentQuery.query('[itemId=a5]')[0];
                        button.expand();
                    },
                    cls: 'btn5'
                },
                {
                    handler: function(button, e) {
                        var button = Ext.ComponentQuery.query('[itemId=a6]')[0];
                        button.expand();
                    },
                    cls: 'btn6'
                },
                {
                    handler: function(button, e) {
                        var button = Ext.ComponentQuery.query('[itemId=a7]')[0];
                        button.expand();
                    },
                    cls: 'btn7'
                }*/
            ],
            listeners: {
                toggle: 'onSegmentedbuttonToggle'
            }
        },
        {
            xtype: 'tbspacer',
            columnWidth: 1,
            height: 80
        }
    ]

});