/*
 * File: app/view/main/MainNorthViewController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Ehm.view.main.MainNorthViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.main_north',

    onSegmentedbuttonToggle: function(segmentedbutton, button, isPressed, eOpts) {
        /*
        var menuPanel = Ext.ComponentQuery.query('panel[itemId=BasicInfo]');
        var itemId = button.itemId;
        if(itemId=='top2'){
        menuPanel = Ext.ComponentQuery.query('panel[itemId=Accounting]');
        } else if(itemId == 'top3'){
        menuPanel = Ext.ComponentQuery.query('panel[itemId=DepositWithraw]');
        } else if(itemId == 'top4'){
        menuPanel = Ext.ComponentQuery.query('panel[itemId=Customer]');
        } else if(itemId == 'top5'){
        menuPanel = Ext.ComponentQuery.query('panel[itemId=Etax]');
        } else if(itemId == 'top6'){
        menuPanel = Ext.ComponentQuery.query('panel[itemId=Salary]');
        }
        menuPanel[0].expand();
        */
    }

});
