/*
 * File: app/view/main/MainWestViewController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Ehm.view.main.MainWestViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.main_west',

    onPanelAfterRender: function(component, eOpts) {
        var me = this.getView().down('#west_detail');

        Ext.Ajax.request({
            url:'./resources/json/menu.json',
            success : function(response){
                var resObj =Ext.decode(response.responseText);
                var arr_temp = [];
                for(var i=0;i<resObj.children.length;i++){
                    var title = resObj.children[i].menuName;
                    var itemid = resObj.children[i].itemId;
                    var prefix ='<span style="text-align:left;" role="presentation" class="'+resObj.children[i].iconCls+'"></span>';
                    var panel = Ext.create('Ehm.view.main.MainWestMenu',{
                        title : prefix+title,
                        itemId: itemid,
                        store: new Ext.data.TreeStore({
                            fields : ['menuName','expanded','leaf'],
                            root : {
                                text : 'root',
                                expanded : true,
                                children : resObj.children[i].children
                            }
                        })

                    });
                    arr_temp.push(panel);

                }
                me.add(arr_temp);

            }
        });
    }

});
