/*
 * File: app/view/main/MainWestMenu.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Ehm.view.main.MainWestMenu', {
    extend: 'Ext.tree.Panel',
    alias: 'widget.main_west_menu',

    requires: [
        'Ehm.view.main.MainWestMenuViewModel',
        'Ehm.view.main.MainWestMenuViewController',
        'Ext.tree.View',
        'Ext.selection.RowModel',
        'Ext.tree.Column'
    ],

    controller: 'main_west_menu',
    viewModel: {
        type: 'main_west_menu'
    },
    defaultListenerScope: true,
    cls: 'menupanel',
    height: 250,
    width: 400,
    title: 'My Tree Panel',
    hideHeaders: true,
    rootVisible: false,

    viewConfig: {
        enableTextSelection: false,
        animate: false,
        rootVisible: false
    },
    selModel: {
        selType: 'rowmodel',
        mode: 'SINGLE'
    },
    columns: [
        {
            xtype: 'treecolumn',
            dataIndex: 'menuName',
            text: 'MyTreeColumn',
            flex: 1
        }
    ],
    listeners: {
        itemclick: 'onTreepanelItemClick',
        collapse: {
            fn: 'onTreepanelCollapse',
            scope: 'controller'
        }
    },

    onTreepanelItemClick: function(dataview, record, item, index, e, eOpts) {
        var className = record.data.className;
        var menuName = record.data.menuName;
        var widgetName = record.data.widgetName;
        var screenID = record.data.screenID;

        if(Ext.isEmpty(widgetName)) return null;

        if(record.data.lev>='2' && Ext.isDefined(widgetName) && Ext.isDefined(screenID)){


            var globalTab = Ext.ComponentQuery.query('#main_tab')[0];
            var activeTab = globalTab.down('[screenID='+screenID+']');
            if(activeTab){
                globalTab.setActiveItem(activeTab);
            }else{
                var newTab = Ext.widget(widgetName,{title : menuName,screenID : screenID});
                globalTab.add(newTab);
                globalTab.setActiveItem(newTab);
            }

        }
    }

});