/*
 * File: app/view/main/MainWest.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Ehm.view.main.MainWest', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.main_west',

    requires: [
        'Ehm.view.main.MainWestViewModel',
        'Ehm.view.main.MainWestViewController',
        'Ext.panel.Panel'
    ],

    controller: 'main_west',
    viewModel: {
        type: 'main_west'
    },
    layout: 'fit',
    title: '메 뉴',

    items: [
        {
            xtype: 'panel',
            itemId: 'west_detail',
            bodyCls: 'defaultpanel',
            layout: {
                type: 'accordion',
                activeOnTop: true
            }
        }
    ],
    listeners: {
        afterrender: 'onPanelAfterRender'
    }

});