/*
 * File: app/store/CommonCodeStore.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Ehm.store.CommonCodeStore', {
    extend: 'Ext.data.Store',
    alias: 'store.common_code_store',

    requires: [
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json',
        'Ext.data.field.Field'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'CommonCodeStore',
            autoLoad: true,
            proxy: {
                type: 'ajax',
                url: '/getCodeList.do',
                reader: {
                    type: 'json'
                }
            },
            fields: [
                {
                    name: 'sq_code'
                },
                {
                    name: 'cd_code_category'
                },
                {
                    name: 'nm_code_category'
                },
                {
                    name: 'cd_code'
                },
                {
                    name: 'nm_code'
                },
                {
                    name: 'val_code'
                },
                {
                    name: 'val_code1'
                },
                {
                    name: 'val_code2'
                },
                {
                    name: 'val_code3'
                },
                {
                    name: 'txt_code'
                },
                {
                    name: 'no_order'
                },
                {
                    name: 'ty_use'
                }
            ]
        }, cfg)]);
    }
});