/*
 * File: app/view/widget/button/WidgetButtonCancel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Ehm.view.widget.button.WidgetButtonCancel', {
    extend: 'Ext.button.Button',
    alias: 'widget.widget_button_cancel',

    icon: './resources/ehm_images/Icons/16x16/Btn_Cancel.png',
    text: '취 소',

    listeners: {
        click: 'onButtonClick'
    },

    onButtonClick: function(button, e, eOpts) {
        button.up('window').destroy();
    }

});